/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_pint.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for I2C1 */
/* Definition of peripheral ID */
#define I2C1_PERIPHERAL ((I2C_Type *)I2C1)
/* Definition of the clock source frequency */
#define I2C1_CLOCK_SOURCE 18000000UL
/* BOARD_InitPeripherals defines for I2C2 */
/* Definition of peripheral ID */
#define I2C2_PERIPHERAL ((I2C_Type *)I2C2)
/* Definition of the clock source frequency */
#define I2C2_CLOCK_SOURCE 18000000UL
/* BOARD_InitPeripherals defines for I2C3 */
/* Definition of peripheral ID */
#define I2C3_PERIPHERAL ((I2C_Type *)I2C3)
/* Definition of the clock source frequency */
#define I2C3_CLOCK_SOURCE 18000000UL
/* BOARD_InitPeripherals defines for PINT */
/* Definition of peripheral ID */
#define PINT_PERIPHERAL ((PINT_Type *) PINT_BASE)
/* Definition of PINT interrupt ID for interrupt 0  */
#define PINT_INT_0 kPINT_PinInt0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2c_master_config_t I2C1_config;
extern const i2c_master_config_t I2C2_config;
extern const i2c_master_config_t I2C3_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* INT_0 callback function for the PINT component */
extern void Wakeup_btn(pint_pin_int_t pintr ,uint32_t pmatch_status);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
